services:
    #see description of listeners https://rmoff.net/2018/08/02/kafka-listeners-explained/
  example-mysql:
    container_name: ziggo-example-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_PASSWORD
    image: mysql:latest
    volumes:
      - ./init-script.sql:/docker-entrypoint-initdb.d/init-script.sql
    networks:
      - ziggo-test-network
  app:
    depends_on:
    - example-mysql
    build: ./
    restart: on-failure
    ports:
      - '8081:8080'
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.datasource.url"  : "jdbc:mysql://example-mysql:3306/orders?allowPublicKeyRetrieval=true&useSSL=false",
          "spring.datasource.username" : "$MYSQLDB_USER",
          "spring.datasource.password" : "$MYSQLDB_PASSWORD",
          "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
          "spring.jpa.hibernate.ddl-auto" : "update"
        }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    networks:
      - ziggo-test-network
networks:
  ziggo-test-network:
