version: "3.7"
services:
  example-mysql:
    container_name: ziggo-example-mysql
    ports:
      - '3306:3306'
    expose:
      - '3306'
    environment:
      - MYSQLDB_USER=$MYSQLDB_USER
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_PASSWORD
      - MYSQL_DATABASE=orders
    image: mysql:latest
    networks:
      - ziggo-test-network
  app:
    depends_on:
    - example-mysql
    build: ./
    restart: on-failure
    ports:
      - '8081:8080'
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.datasource.url"  : "jdbc:mysql://example-mysql:3306/orders?allowPublicKeyRetrieval=true&useSSL=false",
          "spring.datasource.username" : "$MYSQLDB_USER",
          "spring.datasource.password" : "$MYSQLDB_PASSWORD",
          "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
          "spring.jpa.hibernate.ddl-auto" : "update"
        }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    networks:
      - ziggo-test-network
networks:
  ziggo-test-network:
